source: /
collections_config:
  posts:
    path: content/posts
    name: Posts
    icon: edit_note
    disable_url: false
    description: 所有的部落格文章都在這裡
    _inputs:
      $.summary:
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - content
  - visual
base_url: /
timezone: Etc/UTC
