# CloudCannon 導航設定
collections_config:
  posts:
    path: content/posts
    name: Posts
    icon: edit_note
    description: 所有的部落格文章都在這裡

# 編輯器設定
_enabled_editors:
  - content
  - visual

# 指定 Hugo 的基本設定
source: /
base_url: /