# 強行關閉那個討厭的 Lighthouse 插件
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    enabled = false

[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "git submodule update --init --recursive && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.119.0"

[context.branch-deploy]
  command = "git submodule update --init --recursive && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.119.0"

[[redirects]]
  from = "/npmjs/*"
  to = "/npmjs/"
  status = 200